# Generated by Django 4.2.6 on 2023-10-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(verbose_name='Дата создаения заявки')),
                ('customer_name', models.CharField(max_length=50, null=None, verbose_name='Имя клиента')),
                ('customer_surname', models.CharField(max_length=50, null=None, verbose_name='Фамилия клиента')),
                ('customer_email', models.EmailField(max_length=254, null=None, verbose_name='Электронная почта')),
                ('knows_where_to_go', models.BooleanField(null=None, verbose_name='Знает куда лететь')),
                ('country_to_visit', models.CharField(max_length=50, null=None, verbose_name='Страна визита')),
                ('trip_start_date', models.DateField(verbose_name='Дата начала поездки')),
                ('trip_finish_date', models.DateField(verbose_name='Дата завершения поездки')),
            ],
        ),
    ]
